### ISSUE TITLE
Issues with peer dependency versions

### ISSUE THREAD

**Issue by dhruvkb** [ElMassimo/iles#262] opened 2023-09-17 16:08 UTC
**Is your feature request related to a problem? Please describe.**

When installing dependencies in my project, I get 3 issues with peer depdences, all of which are from iles' packages.

<img width="564" alt="Screenshot 2023-09-17 at 8 02 25 PM" src="https://github.com/ElMassimo/iles/assets/16580576/f7a08ebc-7846-4f9b-b9cf-d8a2be545643">

The first of these is especially problematic when `iles` conflicts with its own `@islands/feed` packages.

**Describe the solution you'd like**

A new release with updated versions of underlying dependencies could resolve these peer dependency issues.

**Comment by ouuan** [comment] 2023-09-17 16:10
Duplicate of #214

**Closed** 2023-09-18 12:07 UTC
